FROM php:8.3-fpm

RUN mkdir -p /var/www/holos.backend

WORKDIR /var/www/holos.backend

RUN apt-get update && apt-get install -y\
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev\
    nano \
    openssl

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install --optimize-autoloader --no-interaction --no-scripts

COPY . .

COPY entrypoint-dev.sh /usr/local/bin/entrypoint-dev.sh
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

RUN mkdir -p storage/app/keys storage/logs bootstrap/cache

RUN chown -R www-data:www-data /var/www/holos.backend/storage /var/www/holos.backend/bootstrap/cache
RUN chmod -R 775 /var/www/holos.backend/storage /var/www/holos.backend/bootstrap/cache

EXPOSE 9000

ENTRYPOINT ["/usr/local/bin/entrypoint-dev.sh"]
CMD ["php-fpm"]
