services:
  holos-backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    working_dir: /var/www/holos.backend
    volumes:
      - ./:/var/www/holos.backend
      - ./storage:/var/www/holos.backend/storage
    networks:
      - holos-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/holos.backend/public
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - holos-network
    depends_on:
      - holos-backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - holos-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '${PMA_PORT}:80'
    depends_on:
        - mysql
    networks:
        - holos-network

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
     - holos-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  holos-network:
    driver: bridge
