FROM php:8.3-fpm

RUN mkdir -p /var/www/holos.backend

WORKDIR /var/www/holos.backend

RUN apt-get update && apt-get install -y\
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev\
    nano

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install --optimize-autoloader --no-interaction --no-scripts

COPY . .

# Ejecutar los scripts de Laravel después de copiar el código
RUN composer run-script post-autoload-dump

EXPOSE 9000

CMD ["php-fpm"]
